# Generated by Django 3.0.5 on 2020-04-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200429_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locationid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
