# Generated by Django 3.0.5 on 2020-04-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200429_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='faxnumber',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='officephone',
            field=models.BigIntegerField(),
        ),
    ]
