# Generated by Django 3.0.5 on 2020-04-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200429_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locationid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
