# Generated by Django 3.2.9 on 2021-11-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
